using System;
using System.Text;
using System.Text.RegularExpressions;
using SESpriteLCDLayoutTool.Models;

namespace SESpriteLCDLayoutTool.Services
{
    /// <summary>Target code style for generated output.</summary>
    public enum CodeStyle
    {
        /// <summary>Programmable Block (ingame) script — uses Sandbox.ModAPI.Ingame.</summary>
        InGame,
        /// <summary>C# mod — uses Sandbox.ModAPI (not .Ingame) with full using directives.</summary>
        Mod,
        /// <summary>Torch/Plugin — uses Sandbox.ModAPI with full using directives and session context hints.</summary>
        Plugin,
    }

    public static class CodeGenerator
    {
        /// <summary>
        /// Generates a complete C# method body that draws every sprite in the layout
        /// onto an IMyTextSurface, ready to paste into an SE plugin, mod, or ingame script.
        /// </summary>
        public static string Generate(LcdLayout layout,
                                      CodeStyle style     = CodeStyle.InGame,
                                      string methodName   = "DrawLayout",
                                      string surfaceParam = "surface")
        {
            var sb = new StringBuilder();

            sb.AppendLine($"// ─── Generated by SE Sprite LCD Layout Tool  [{DateTime.Now:yyyy-MM-dd HH:mm}] ───");
            sb.AppendLine($"// Surface: {layout.SurfaceWidth} × {layout.SurfaceHeight}  |  Sprites: {layout.Sprites.Count}");
            sb.AppendLine("//");

            switch (style)
            {
                case CodeStyle.Mod:
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextSurface");
                    sb.AppendLine("//");
                    sb.AppendLine("// NOTE: Mod code — use IMyTextSurface from Sandbox.ModAPI (not .Ingame).");
                    break;

                case CodeStyle.Plugin:
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextSurface");
                    sb.AppendLine("//");
                    sb.AppendLine("// NOTE: Plugin/Torch code — obtain an IMyTextSurface from a terminal block:");
                    sb.AppendLine("//   var lcd = block as IMyTextSurfaceProvider;");
                    sb.AppendLine("//   var surface = lcd?.GetSurface(0);");
                    break;

                default: // InGame / PB
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI.Ingame;      // IMyTextSurface  (ingame scripts only)");
                    break;
            }

            sb.AppendLine("//");
            sb.AppendLine("// Sprite positions are the CENTER of each sprite in surface-local pixel coordinates.");
            sb.AppendLine("// For surfaces that do not fill the full texture (small LCDs, corner blocks) you");
            sb.AppendLine("// may need to add the viewport offset:  var ofs = (surface.TextureSize - surface.SurfaceSize) / 2f;");
            sb.AppendLine();

            string access = style == CodeStyle.InGame ? "private" : "public";
            sb.AppendLine($"{access} void {methodName}(IMyTextSurface {surfaceParam})");
            sb.AppendLine("{");
            sb.AppendLine($"    {surfaceParam}.ContentType = ContentType.SCRIPT;");
            sb.AppendLine($"    {surfaceParam}.Script = \"\";");
            sb.AppendLine();
            sb.AppendLine($"    using (var frame = {surfaceParam}.DrawFrame())");
            sb.AppendLine("    {");

            if (layout.Sprites.Count == 0)
            {
                sb.AppendLine("        // No sprites in layout — add some in the designer!");
            }
            else
            {
                for (int i = 0; i < layout.Sprites.Count; i++)
                {
                    var sp = layout.Sprites[i];
                    sb.AppendLine($"        // [{i + 1}] {sp.DisplayName}");
                    sb.AppendLine("        frame.Add(new MySprite");
                    sb.AppendLine("        {");

                    if (sp.Type == SpriteEntryType.Text)
                    {
                        sb.AppendLine($"            Type           = SpriteType.TEXT,");
                        sb.AppendLine($"            Data           = {Q(sp.Text)},");
                        if (sp.IsReferenceLayout)
                            sb.AppendLine($"            // Position  = new Vector2({sp.X:F1}f, {sp.Y:F1}f),  // snapshot reference — replace with your variable");
                        else
                            sb.AppendLine($"            Position       = new Vector2({sp.X:F1}f, {sp.Y:F1}f),");
                        sb.AppendLine($"            Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                        sb.AppendLine($"            FontId         = {Q(sp.FontId)},");
                        sb.AppendLine($"            Alignment      = TextAlignment.{sp.Alignment.ToString().ToUpperInvariant()},");
                        sb.AppendLine($"            RotationOrScale = {sp.Scale:F2}f,  // scale for TEXT sprites");
                    }
                    else
                    {
                        sb.AppendLine($"            Type           = SpriteType.TEXTURE,");
                        sb.AppendLine($"            Data           = {Q(sp.SpriteName)},");
                        if (sp.IsReferenceLayout)
                        {
                            sb.AppendLine($"            // Position  = new Vector2({sp.X:F1}f, {sp.Y:F1}f),  // snapshot reference");
                            sb.AppendLine($"            // Size      = new Vector2({sp.Width:F1}f, {sp.Height:F1}f),  // snapshot reference");
                        }
                        else
                        {
                            sb.AppendLine($"            Position       = new Vector2({sp.X:F1}f, {sp.Y:F1}f),");
                            sb.AppendLine($"            Size           = new Vector2({sp.Width:F1}f, {sp.Height:F1}f),");
                        }
                        sb.AppendLine($"            Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                        sb.AppendLine($"            Alignment      = TextAlignment.CENTER,");
                        sb.AppendLine($"            RotationOrScale = {sp.Rotation:F4}f,  // radians");
                    }

                    sb.AppendLine("        });");

                    if (i < layout.Sprites.Count - 1)
                        sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string Q(string s)   => $"\"{Esc(s)}\"";

        /// <summary>
        /// Generates a C# helper method that the user can drop into their PB/mod/plugin.
        /// When called at runtime, it serializes every sprite currently on a surface
        /// into literal MySprite initializer code that the layout tool can import
        /// with exact positions.
        /// </summary>
        public static string GenerateSnapshotHelper(CodeStyle style = CodeStyle.InGame)
        {
            switch (style)
            {
                case CodeStyle.Plugin:  return GenerateSnapshotHelper_Plugin();
                case CodeStyle.Mod:     return GenerateSnapshotHelper_Mod();
                default:                return GenerateSnapshotHelper_PB();
            }
        }

        private static string GenerateSnapshotHelper_PB()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Programmable Block) ───────────────────────────");
            sb.AppendLine("// Drop this into your PB script.  After your drawing code, call:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   Me.CustomData = SerializeSnapshot();");
            sb.AppendLine("// Then copy the PB's Custom Data and paste into the layout tool's");
            sb.AppendLine("// \"Paste Layout\" dialog with \"Import as reference layout\" checked.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "");
            sb.AppendLine();
            sb.AppendLine("// ── Usage in your PB Main() ──");
            sb.AppendLine("// After your drawing loop:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   Me.CustomData = SerializeSnapshot();");
            return sb.ToString();
        }

        private static string GenerateSnapshotHelper_Mod()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Mod) ─────────────────────────────────────────");
            sb.AppendLine("// Add this to your mod's session component or drawing class.");
            sb.AppendLine("// After your rendering code, call:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   var output = SerializeSnapshot();");
            sb.AppendLine("//   MyAPIGateway.Utilities.ShowMissionScreen(\"Snapshot\", \"\", \"\", output);");
            sb.AppendLine("// Copy from the mission screen and paste into the layout tool.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System.Text;");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;");
            sb.AppendLine("//   using VRageMath;");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "public ");
            return sb.ToString();
        }

        private static string GenerateSnapshotHelper_Plugin()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Torch / Plugin) ──────────────────────────────");
            sb.AppendLine("// Add this to your plugin class.  Wire up SnapshotLcd() to a chat");
            sb.AppendLine("// command (e.g. !snapshot) or call it from your rendering code.");
            sb.AppendLine("//");
            sb.AppendLine("// The snapshot is written to a file and logged via NLog so you can");
            sb.AppendLine("// grab it from the Torch console or the output file.");
            sb.AppendLine("// Paste the output into the layout tool's \"Paste Layout\" dialog");
            sb.AppendLine("// with \"Import as reference layout\" checked.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System.Collections.Generic;");
            sb.AppendLine("//   using System.IO;");
            sb.AppendLine("//   using System.Text;");
            sb.AppendLine("//   using NLog;");
            sb.AppendLine("//   using Sandbox.ModAPI;");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;");
            sb.AppendLine("//   using VRageMath;");
            sb.AppendLine();
            sb.AppendLine("private static readonly Logger Log = LogManager.GetCurrentClassLogger();");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "public ");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Snapshots all sprites currently on a surface and writes them to a file.");
            sb.AppendLine("/// Call from a chat command handler, e.g.:");
            sb.AppendLine("///   var lcd = block as IMyTextSurfaceProvider;");
            sb.AppendLine("///   SnapshotLcd(lcd?.GetSurface(0), \"MyLcdSnapshot\");");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void SnapshotLcd(IMyTextSurface surface, string label = \"LcdSnapshot\")");
            sb.AppendLine("{");
            sb.AppendLine("    if (surface == null) { Log.Warn(\"SnapshotLcd: surface is null\"); return; }");
            sb.AppendLine();
            sb.AppendLine("    // NOTE: SE doesn't expose a way to read back an already-drawn frame.");
            sb.AppendLine("    // You need to collect sprites BEFORE adding them to the frame.");
            sb.AppendLine("    // Call SnapshotCollect(sprites) in your rendering code first.");
            sb.AppendLine("    if (_snapshotSprites.Count == 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn(\"SnapshotLcd: no sprites collected — call SnapshotCollect() first\");");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    string output = SerializeSnapshot();");
            sb.AppendLine("    string path = Path.Combine(");
            sb.AppendLine("        StoragePath ?? Directory.GetCurrentDirectory(),");
            sb.AppendLine("        $\"{label}_{DateTime.Now:yyyyMMdd_HHmmss}.txt\");");
            sb.AppendLine();
            sb.AppendLine("    File.WriteAllText(path, output);");
            sb.AppendLine("    Log.Info($\"LCD snapshot saved: {path}  ({_snapshotSprites.Count} sprites)\");");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Appends the shared SnapshotCollect + SerializeSnapshot methods.
        /// </summary>
        private static void AppendSnapshotCore(StringBuilder sb, string accessModifier)
        {
            // The snapshot collector list
            sb.AppendLine($"{accessModifier}List<MySprite> _snapshotSprites = new List<MySprite>();");
            sb.AppendLine();

            // Collect method
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Call this with your list of MySprite objects after you've built them");
            sb.AppendLine("/// but before (or after) adding them to the frame.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotCollect(List<MySprite> sprites)");
            sb.AppendLine("{");
            sb.AppendLine("    _snapshotSprites.Clear();");
            sb.AppendLine("    _snapshotSprites.AddRange(sprites);");
            sb.AppendLine("}");
            sb.AppendLine();

            // Serializer
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Serializes collected sprites into C# MySprite initializer code");
            sb.AppendLine("/// with all positions/sizes resolved to literal pixel values.");
            sb.AppendLine("/// Paste the output into the layout tool's \"Paste Layout\" dialog.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}string SerializeSnapshot()");
            sb.AppendLine("{");
            sb.AppendLine("    var sb = new StringBuilder();");
            sb.AppendLine("    sb.AppendLine(\"// ── LCD Snapshot ──\");");
            sb.AppendLine("    sb.AppendLine($\"// Captured: {DateTime.Now:yyyy-MM-dd HH:mm}  |  Sprites: {_snapshotSprites.Count}\");");
            sb.AppendLine("    sb.AppendLine();");
            sb.AppendLine("    for (int i = 0; i < _snapshotSprites.Count; i++)");
            sb.AppendLine("    {");
            sb.AppendLine("        var s = _snapshotSprites[i];");
            sb.AppendLine("        sb.AppendLine(\"frame.Add(new MySprite\");");
            sb.AppendLine("        sb.AppendLine(\"{\");");
            sb.AppendLine("        sb.AppendLine($\"    Type           = SpriteType.{s.Type},\");");
            sb.AppendLine("        sb.AppendLine($\"    Data           = \\\"{s.Data}\\\",\");");
            sb.AppendLine("        if (s.Position.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Position       = new Vector2({s.Position.Value.X:F1}f, {s.Position.Value.Y:F1}f),\");");
            sb.AppendLine("        if (s.Size.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Size           = new Vector2({s.Size.Value.X:F1}f, {s.Size.Value.Y:F1}f),\");");
            sb.AppendLine("        if (s.Color.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Color          = new Color({s.Color.Value.R}, {s.Color.Value.G}, {s.Color.Value.B}, {s.Color.Value.A}),\");");
            sb.AppendLine("        if (s.FontId != null)");
            sb.AppendLine("            sb.AppendLine($\"    FontId         = \\\"{s.FontId}\\\",\");");
            sb.AppendLine("        sb.AppendLine($\"    Alignment      = TextAlignment.{s.Alignment},\");");
            sb.AppendLine("        sb.AppendLine($\"    RotationOrScale = {s.RotationOrScale:F4}f,\");");
            sb.AppendLine("        sb.AppendLine(\"});\");");
            sb.AppendLine("        sb.AppendLine();");
            sb.AppendLine("    }");
            sb.AppendLine("    return sb.ToString();");
            sb.AppendLine("}");
        }
        /// <summary>
        /// Escapes a string for a C# string literal, turning any PUA or non-ASCII
        /// character into a \uXXXX escape so the generated code is always ASCII-safe.
        /// </summary>
        private static string Esc(string s)
        {
            if (s == null) return "";
            var sb = new StringBuilder(s.Length * 2);
            foreach (char c in s)
            {
                if (c == '\\') { sb.Append("\\\\"); }
                else if (c == '"') { sb.Append("\\\""); }
                else if (c >= 0x007F)  // non-ASCII or PUA → \uXXXX
                    sb.Append($"\\u{(int)c:X4}");
                else
                    sb.Append(c);
            }
            return sb.ToString();
        }

        // ── Per-sprite dynamic round-trip ─────────────────────────────────────

        /// <summary>
        /// Per-sprite property patching for dynamic code (loops, switch/case, expressions).
        /// Compares each sprite's current values against its ImportBaseline and surgically
        /// replaces only the literal values (colors, textures, fonts) that changed,
        /// preserving all dynamic expressions and surrounding code.
        /// Returns null if per-sprite patching is not applicable.
        /// </summary>
        public static string PatchOriginalSource(LcdLayout layout)
        {
            string original = layout.OriginalSourceCode;
            if (string.IsNullOrWhiteSpace(original)) return null;

            // Collect sprites that have source tracking and a baseline
            var patchable = new System.Collections.Generic.List<SpriteEntry>();
            foreach (var sp in layout.Sprites)
            {
                if (sp.IsReferenceLayout) continue;
                if (sp.SourceStart < 0 || sp.SourceEnd < 0 || sp.ImportBaseline == null) continue;
                patchable.Add(sp);
            }

            if (patchable.Count == 0) return null;

            // Sort by SourceStart descending so we patch from end-to-start (preserves offsets)
            patchable.Sort((a, b) => b.SourceStart.CompareTo(a.SourceStart));

            var result = new StringBuilder(original);

            foreach (var sp in patchable)
            {
                var bl = sp.ImportBaseline;
                if (sp.SourceStart >= result.Length || sp.SourceEnd > result.Length) continue;

                string chunk = result.ToString(sp.SourceStart, sp.SourceEnd - sp.SourceStart);
                string patched = chunk;

                // Patch texture/sprite name (string literal)
                if (sp.Type == SpriteEntryType.Texture &&
                    bl.SpriteName != sp.SpriteName &&
                    bl.SpriteName != null && sp.SpriteName != null)
                {
                    patched = ReplaceStringLiteral(patched, bl.SpriteName, sp.SpriteName);
                }

                // Patch text content (string literal)
                if (sp.Type == SpriteEntryType.Text &&
                    bl.Text != sp.Text &&
                    bl.Text != null && sp.Text != null)
                {
                    patched = ReplaceStringLiteral(patched, bl.Text, sp.Text);
                }

                // Patch font name (string literal)
                if (bl.FontId != sp.FontId &&
                    bl.FontId != null && sp.FontId != null)
                {
                    patched = ReplaceStringLiteral(patched, bl.FontId, sp.FontId);
                }

                // Patch color (new Color(...) literals or named colors like Color.White)
                if (bl.ColorR != sp.ColorR || bl.ColorG != sp.ColorG ||
                    bl.ColorB != sp.ColorB || bl.ColorA != sp.ColorA)
                {
                    patched = PatchColorLiteral(patched, bl, sp);
                }

                // Only substitute if something actually changed
                if (patched != chunk)
                {
                    result.Remove(sp.SourceStart, sp.SourceEnd - sp.SourceStart);
                    result.Insert(sp.SourceStart, patched);
                }
            }

            string final = result.ToString();
            // Return the (possibly unchanged) original — null only when patching is not applicable
            return final;
        }

        /// <summary>Replaces a quoted string literal in the source text.</summary>
        private static string ReplaceStringLiteral(string text, string oldValue, string newValue)
        {
            string escapedOld = $"\"{Esc(oldValue)}\"";
            string escapedNew = $"\"{Esc(newValue)}\"";
            int idx = text.IndexOf(escapedOld, StringComparison.Ordinal);
            if (idx < 0) return text;
            return text.Substring(0, idx) + escapedNew + text.Substring(idx + escapedOld.Length);
        }

        /// <summary>
        /// Patches a color literal in the source text. Handles new Color(R,G,B),
        /// new Color(R,G,B,A), and named colors like Color.White.
        /// </summary>
        private static string PatchColorLiteral(string text, SpriteEntry baseline, SpriteEntry current)
        {
            string newColor = current.ColorA != 255
                ? $"new Color({current.ColorR}, {current.ColorG}, {current.ColorB}, {current.ColorA})"
                : $"new Color({current.ColorR}, {current.ColorG}, {current.ColorB})";

            // Try matching "new Color(R, G, B)" or "new Color(R, G, B, A)"
            var colorPattern = new Regex(
                @"new\s+Color\s*\(\s*" + baseline.ColorR + @"\s*,\s*" + baseline.ColorG +
                @"\s*,\s*" + baseline.ColorB + @"(?:\s*,\s*\d+)?\s*\)");

            if (colorPattern.IsMatch(text))
                return colorPattern.Replace(text, newColor, 1);

            // Try named colors: Color.White → (255,255,255), Color.Red → (255,0,0), etc.
            string namedColor = MatchNamedColor(baseline);
            if (namedColor != null)
            {
                int idx = text.IndexOf(namedColor, StringComparison.Ordinal);
                if (idx >= 0)
                    return text.Substring(0, idx) + newColor + text.Substring(idx + namedColor.Length);
            }

            return text; // color is an expression — can't patch
        }

        /// <summary>Returns the C# named color expression that matches the baseline values, or null.</summary>
        private static string MatchNamedColor(SpriteEntry bl)
        {
            if (bl.ColorA == 255)
            {
                if (bl.ColorR == 255 && bl.ColorG == 255 && bl.ColorB == 255) return "Color.White";
                if (bl.ColorR == 0   && bl.ColorG == 0   && bl.ColorB == 0)   return "Color.Black";
                if (bl.ColorR == 255 && bl.ColorG == 0   && bl.ColorB == 0)   return "Color.Red";
                if (bl.ColorR == 0   && bl.ColorG == 255 && bl.ColorB == 0)   return "Color.Green";
                if (bl.ColorR == 0   && bl.ColorG == 0   && bl.ColorB == 255) return "Color.Blue";
                if (bl.ColorR == 255 && bl.ColorG == 255 && bl.ColorB == 0)   return "Color.Yellow";
            }
            if (bl.ColorR == 0 && bl.ColorG == 0 && bl.ColorB == 0 && bl.ColorA == 0)
                return "Color.Transparent";
            return null;
        }

        /// <summary>
        /// Detects the surrounding code context for a sprite at a given position.
        /// Looks backwards for case labels, method names, or region comments.
        /// Returns a label like "Header", "Item", "Footer" or null.
        /// </summary>
        public static string DetectSpriteContext(string code, int position)
        {
            if (code == null || position <= 0) return null;

            string before = code.Substring(0, Math.Min(position, code.Length));

            // Look for nearest "case ...:Kind.XYZ:" or "case ...XYZ:" pattern
            var caseMatch = Regex.Match(before,
                @"case\s+(?:\w+\.)*(\w+)\s*:", RegexOptions.RightToLeft);
            if (caseMatch.Success)
                return caseMatch.Groups[1].Value;

            return null;
        }

        // ── Region-based round-trip (static layouts) ──────────────────────────

        /// <summary>
        /// When OriginalSourceCode is set, splices updated sprite definitions back
        /// into the original pasted code so the user can paste straight back into
        /// their project. Returns null if round-trip is not possible.
        /// </summary>
        public static string GenerateRoundTrip(LcdLayout layout)
        {
            string original = layout.OriginalSourceCode;
            if (string.IsNullOrWhiteSpace(original) || layout.Sprites.Count == 0)
                return null;

            // Find all MySprite definitions in the original code.
            // Match: new MySprite { ... }, new MySprite(...), MySprite.CreateText(...), MySprite.CreateSprite(...)
            var spritePattern = new Regex(
                @"(new\s+MySprite\s*[\({])|(MySprite\s*\.\s*Create(?:Text|Sprite)\s*\()",
                RegexOptions.Compiled);

            var matches = spritePattern.Matches(original);
            if (matches.Count == 0) return null;

            // Region start: beginning of the LINE containing the first MySprite match.
            // This ensures we capture "frame.Add(" or similar prefixes on the same line.
            // Also absorb any preceding comment/blank lines (like "// [1] SquareSimple").
            int firstMatchPos = matches[0].Index;
            int regionStart = FindLineStart(original, firstMatchPos);
            regionStart = AbsorbPrecedingComments(original, regionStart);

            // Region end: after the last MySprite block's closing punctuation
            int regionEnd = -1;
            for (int i = matches.Count - 1; i >= 0; i--)
            {
                string matchText = matches[i].Value;
                char lastChar = matchText[matchText.Length - 1];

                if (lastChar == '{')
                {
                    int braceEnd = FindMatchingBrace(original, matches[i].Index + matchText.Length - 1);
                    if (braceEnd >= 0)
                        regionEnd = SkipTrailingPunctuation(original, braceEnd + 1);
                }
                else // '(' — constructor or factory method
                {
                    int parenEnd = FindMatchingParen(original, matches[i].Index + matchText.Length - 1);
                    if (parenEnd >= 0)
                        regionEnd = SkipTrailingPunctuation(original, parenEnd + 1);
                }

                if (regionEnd > 0) break;
            }

            if (regionEnd <= regionStart) return null;

            // Detect indentation from the line containing the first MySprite match
            string indent = DetectIndent(original, firstMatchPos);

            // Generate just the sprite definitions with the detected indentation
            var sb = new StringBuilder();
            int actualCount = 0;
            for (int i = 0; i < layout.Sprites.Count; i++)
            {
                var sp = layout.Sprites[i];
                if (sp.IsReferenceLayout) continue;

                if (actualCount > 0) sb.AppendLine();

                sb.AppendLine($"{indent}// [{actualCount + 1}] {sp.DisplayName}");
                sb.AppendLine($"{indent}frame.Add(new MySprite");
                sb.AppendLine($"{indent}{{");

                if (sp.Type == SpriteEntryType.Text)
                {
                    sb.AppendLine($"{indent}    Type           = SpriteType.TEXT,");
                    sb.AppendLine($"{indent}    Data           = {Q(sp.Text)},");
                    sb.AppendLine($"{indent}    Position       = new Vector2({sp.X:F1}f, {sp.Y:F1}f),");
                    sb.AppendLine($"{indent}    Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                    sb.AppendLine($"{indent}    FontId         = {Q(sp.FontId)},");
                    sb.AppendLine($"{indent}    Alignment      = TextAlignment.{sp.Alignment.ToString().ToUpperInvariant()},");
                    sb.AppendLine($"{indent}    RotationOrScale = {sp.Scale:F2}f,");
                }
                else
                {
                    sb.AppendLine($"{indent}    Type           = SpriteType.TEXTURE,");
                    sb.AppendLine($"{indent}    Data           = {Q(sp.SpriteName)},");
                    sb.AppendLine($"{indent}    Position       = new Vector2({sp.X:F1}f, {sp.Y:F1}f),");
                    sb.AppendLine($"{indent}    Size           = new Vector2({sp.Width:F1}f, {sp.Height:F1}f),");
                    sb.AppendLine($"{indent}    Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                    sb.AppendLine($"{indent}    Alignment      = TextAlignment.CENTER,");
                    sb.AppendLine($"{indent}    RotationOrScale = {sp.Rotation:F4}f,");
                }

                sb.Append($"{indent}}});");
                actualCount++;
            }

            if (actualCount == 0) return null;

            // Ensure the splice ends with a newline
            sb.AppendLine();

            // Splice: original[0..regionStart) + generated + original[regionEnd..)
            string before = original.Substring(0, regionStart);
            string after  = original.Substring(regionEnd);

            return before + sb.ToString() + after;
        }

        /// <summary>Finds the position of the start of the line containing <paramref name="position"/>.</summary>
        private static int FindLineStart(string code, int position)
        {
            int i = position;
            while (i > 0 && code[i - 1] != '\n')
                i--;
            return i;
        }

        /// <summary>
        /// From a line start position, walks backwards to absorb any preceding
        /// comment lines or blank lines that are part of the sprite block.
        /// </summary>
        private static int AbsorbPrecedingComments(string code, int lineStart)
        {
            int pos = lineStart;
            while (pos > 0)
            {
                // Find the start of the preceding line
                int prevEnd = pos - 1; // char before current '\n'
                if (prevEnd >= 0 && code[prevEnd] == '\n') prevEnd--; // skip \n
                if (prevEnd >= 0 && code[prevEnd] == '\r') prevEnd--; // skip \r

                int prevStart = prevEnd;
                while (prevStart > 0 && code[prevStart - 1] != '\n')
                    prevStart--;
                if (prevStart < 0) prevStart = 0;

                // Get the trimmed content of the preceding line
                string prevLine = code.Substring(prevStart, prevEnd - prevStart + 1).Trim();

                // Absorb comment lines and blank lines
                if (prevLine.Length == 0 || prevLine.StartsWith("//"))
                    pos = prevStart;
                else
                    break;
            }
            return pos;
        }

        private static string DetectIndent(string code, int position)
        {
            // Walk backwards from position to find the start of the line
            int lineStart = position;
            while (lineStart > 0 && code[lineStart - 1] != '\n')
                lineStart--;

            // Extract leading whitespace
            var indent = new StringBuilder();
            for (int i = lineStart; i < position && i < code.Length; i++)
            {
                if (code[i] == ' ' || code[i] == '\t')
                    indent.Append(code[i]);
                else
                    break;
            }
            return indent.ToString();
        }

        private static int SkipTrailingPunctuation(string code, int pos)
        {
            // Skip whitespace, ");", ",", or ";" after a closing brace/paren
            while (pos < code.Length)
            {
                char c = code[pos];
                if (c == ')' || c == ';' || c == ',' || c == ' ' || c == '\t')
                    pos++;
                else if (c == '\r' || c == '\n')
                {
                    pos++;
                    break;
                }
                else
                    break;
            }
            // Consume trailing newline
            if (pos < code.Length && code[pos] == '\n') pos++;
            return pos;
        }

        private static int FindMatchingBrace(string code, int openPos)
        {
            int depth = 1;
            for (int i = openPos + 1; i < code.Length; i++)
            {
                if (code[i] == '{') depth++;
                else if (code[i] == '}') { depth--; if (depth == 0) return i; }
            }
            return -1;
        }

        private static int FindMatchingParen(string code, int openPos)
        {
            int depth = 1;
            for (int i = openPos + 1; i < code.Length; i++)
            {
                if (code[i] == '(') depth++;
                else if (code[i] == ')') { depth--; if (depth == 0) return i; }
            }
            return -1;
        }
    }
}
