using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using SESpriteLCDLayoutTool.Models;

namespace SESpriteLCDLayoutTool.Services
{
    /// <summary>Target code style for generated output.</summary>
    public enum CodeStyle
    {
        /// <summary>Programmable Block (ingame) script — uses Sandbox.ModAPI.Ingame.</summary>
        InGame,
        /// <summary>C# mod — uses Sandbox.ModAPI (not .Ingame) with full using directives.</summary>
        Mod,
        /// <summary>Torch/Plugin — uses Sandbox.ModAPI with full using directives and session context hints.</summary>
        Plugin,
        /// <summary>Pulsar plugin — uses VRage.Plugins.IPlugin with Init/Update/Dispose lifecycle.</summary>
        Pulsar,
    }

    public static partial class CodeGenerator
    {
        /// <summary>
        /// Generates a complete C# method body that draws every sprite in the layout
        /// onto an IMyTextSurface, ready to paste into an SE plugin, mod, or ingame script.
        /// </summary>
        public static string Generate(LcdLayout layout,
                                      CodeStyle style     = CodeStyle.InGame,
                                      string methodName   = "DrawLayout",
                                      string surfaceParam = "surface")
        {
            var sb = new StringBuilder();
            var visibleSprites = layout.Sprites.FindAll(sp => !sp.IsHidden);

            sb.AppendLine($"// ─── Generated by SE Sprite LCD Layout Tool  [{DateTime.Now:yyyy-MM-dd HH:mm}] ───");
            sb.AppendLine($"// Surface: {layout.SurfaceWidth} × {layout.SurfaceHeight}  |  Sprites: {visibleSprites.Count}");
            sb.AppendLine("//");

            switch (style)
            {
                case CodeStyle.Mod:
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextSurface");
                    sb.AppendLine("//");
                    sb.AppendLine("// NOTE: Mod code — use IMyTextSurface from Sandbox.ModAPI (not .Ingame).");
                    break;

                case CodeStyle.Plugin:
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextSurface");
                    sb.AppendLine("//");
                    sb.AppendLine("// NOTE: Plugin/Torch code — obtain an IMyTextSurface from a terminal block:");
                    sb.AppendLine("//   var lcd = block as IMyTextSurfaceProvider;");
                    sb.AppendLine("//   var surface = lcd?.GetSurface(0);");
                    break;

                case CodeStyle.Pulsar:
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextPanel");
                    sb.AppendLine("//   using VRage.Plugins;              // IPlugin");
                    sb.AppendLine("//");
                    sb.AppendLine("// NOTE: Pulsar plugin — implement IPlugin with Init/Update/Dispose.");
                    sb.AppendLine("//   Find your LCD panel by scanning grids via MyEntities.GetEntities():");
                    sb.AppendLine("//   foreach (MyEntity e in MyEntities.GetEntities())");
                    sb.AppendLine("//   {");
                    sb.AppendLine("//       var grid = e as MyCubeGrid;");
                    sb.AppendLine("//       if (grid == null) continue;");
                    sb.AppendLine("//       foreach (var slim in grid.CubeBlocks)");
                    sb.AppendLine("//       {");
                    sb.AppendLine("//           var panel = slim.FatBlock as IMyTextPanel;");
                    sb.AppendLine("//           if (panel != null && panel.CustomName == \"YourLCD\")");
                    sb.AppendLine("//               surface = panel;");
                    sb.AppendLine("//       }");
                    sb.AppendLine("//   }");
                    break;

                default: // InGame / PB
                    sb.AppendLine("// Required using directives:");
                    sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // SpriteType, MySprite, ContentType");
                    sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
                    sb.AppendLine("//   using Sandbox.ModAPI.Ingame;      // IMyTextSurface  (ingame scripts only)");
                    break;
            }

            sb.AppendLine("//");
            sb.AppendLine("// Sprite positions are the CENTER of each sprite in surface-local pixel coordinates.");
            sb.AppendLine("// For surfaces that do not fill the full texture (small LCDs, corner blocks) you");
            sb.AppendLine("// may need to add the viewport offset:  var ofs = (surface.TextureSize - surface.SurfaceSize) / 2f;");
            sb.AppendLine();

            string access = style == CodeStyle.InGame ? "private" : "public";
            sb.AppendLine($"{access} void {methodName}(IMyTextSurface {surfaceParam})");
            sb.AppendLine("{");
            sb.AppendLine($"    {surfaceParam}.ContentType = ContentType.SCRIPT;");
            sb.AppendLine($"    {surfaceParam}.Script = \"\";");
            sb.AppendLine();
            sb.AppendLine($"    using (var frame = {surfaceParam}.DrawFrame())");
            sb.AppendLine("    {");

            if (visibleSprites.Count == 0)
            {
                sb.AppendLine("        // No visible sprites in layout — add some in the designer!");
            }
            else
            {
                for (int i = 0; i < visibleSprites.Count; i++)
                {
                    var sp = visibleSprites[i];
                    sb.AppendLine($"        // [{i + 1}] {sp.DisplayName}");
                    sb.AppendLine("        frame.Add(new MySprite");
                    sb.AppendLine("        {");

                    if (sp.Type == SpriteEntryType.Text)
                    {
                        sb.AppendLine($"            Type           = SpriteType.TEXT,");
                        sb.AppendLine($"            Data           = {Q(sp.Text)},");
                        if (sp.IsReferenceLayout)
                            sb.AppendLine($"            // Position  = new Vector2({sp.X:F4}f, {sp.Y:F4}f),  // snapshot reference — replace with your variable");
                        else
                            sb.AppendLine($"            Position       = new Vector2({sp.X:F4}f, {sp.Y:F4}f),");
                        sb.AppendLine($"            Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                        sb.AppendLine($"            FontId         = {Q(sp.FontId)},");
                        sb.AppendLine($"            Alignment      = TextAlignment.{sp.Alignment.ToString().ToUpperInvariant()},");
                        sb.AppendLine($"            RotationOrScale = {sp.Scale:F2}f,  // scale for TEXT sprites");
                    }
                    else
                    {
                        sb.AppendLine($"            Type           = SpriteType.TEXTURE,");
                        sb.AppendLine($"            Data           = {Q(sp.SpriteName)},");
                        if (sp.IsReferenceLayout)
                        {
                            sb.AppendLine($"            // Position  = new Vector2({sp.X:F4}f, {sp.Y:F4}f),  // snapshot reference");
                            sb.AppendLine($"            // Size      = new Vector2({sp.Width:F4}f, {sp.Height:F4}f),  // snapshot reference");
                        }
                        else
                        {
                            sb.AppendLine($"            Position       = new Vector2({sp.X:F4}f, {sp.Y:F4}f),");
                            sb.AppendLine($"            Size           = new Vector2({sp.Width:F4}f, {sp.Height:F4}f),");
                        }
                        sb.AppendLine($"            Color          = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                        sb.AppendLine($"            Alignment      = TextAlignment.CENTER,");
                        sb.AppendLine($"            RotationOrScale = {sp.Rotation:F4}f,  // radians");
                    }

                    sb.AppendLine("        });");

                    if (i < visibleSprites.Count - 1)
                        sb.AppendLine();
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string Q(string s)   => $"\"{Esc(s)}\"";

        /// <summary>
        /// Generates a C# helper method that the user can drop into their PB/mod/plugin.
        /// When called at runtime, it serializes every sprite currently on a surface
        /// into literal MySprite initializer code that the layout tool can import
        /// with exact positions.
        /// </summary>
        public static string GenerateSnapshotHelper(CodeStyle style = CodeStyle.InGame)
        {
            switch (style)
            {
                case CodeStyle.Pulsar:  return GenerateSnapshotHelper_Pulsar();
                case CodeStyle.Plugin:  return GenerateSnapshotHelper_Plugin();
                case CodeStyle.Mod:     return GenerateSnapshotHelper_Mod();
                default:                return GenerateSnapshotHelper_PB();
            }
        }

        private static string GenerateSnapshotHelper_PB()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Programmable Block) ───────────────────────────");
            sb.AppendLine("// Drop this into your PB script.  After your drawing code, call:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   Me.CustomData = SerializeSnapshot();");
            sb.AppendLine("// Then copy the PB's Custom Data and paste into the layout tool's");
            sb.AppendLine("// \"Paste Layout\" dialog with \"Import as reference layout\" checked.");
            sb.AppendLine("//");
            sb.AppendLine("// Debug Variables:  Call SnapshotDebug(\"name\", value) before");
            sb.AppendLine("// SerializeSnapshot() to stream field values into the layout tool's");
            sb.AppendLine("// Variables tab for live debugging.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "");
            sb.AppendLine();
            sb.AppendLine("// ── Usage in your PB Main() ──");
            sb.AppendLine("// After your drawing loop:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   Me.CustomData = SerializeSnapshot();");
            return sb.ToString();
        }

        private static string GenerateSnapshotHelper_Mod()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Mod) ─────────────────────────────────────────");
            sb.AppendLine("// Add this to your mod's session component or drawing class.");
            sb.AppendLine("// After your rendering code, call:");
            sb.AppendLine("//   SnapshotCollect(mySprites);");
            sb.AppendLine("//   var output = SerializeSnapshot();");
            sb.AppendLine("//   MyAPIGateway.Utilities.ShowMissionScreen(\"Snapshot\", \"\", \"\", output);");
            sb.AppendLine("// Copy from the mission screen and paste into the layout tool.");
            sb.AppendLine("//");
            sb.AppendLine("// Debug Variables:  Call SnapshotDebug(\"name\", value) before");
            sb.AppendLine("// SerializeSnapshot() to stream field values into the layout tool's");
            sb.AppendLine("// Variables tab for live debugging.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System.Collections.Generic;");
            sb.AppendLine("//   using System.Text;");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;");
            sb.AppendLine("//   using VRageMath;");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "public ");
            return sb.ToString();
        }

        private static string GenerateSnapshotHelper_Plugin()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Torch / Plugin) ──────────────────────────────");
            sb.AppendLine("// Add this to your plugin class.  Wire up SnapshotLcd() to a chat");
            sb.AppendLine("// command (e.g. !snapshot) or call it from your rendering code.");
            sb.AppendLine("//");
            sb.AppendLine("// The snapshot is written to a file and logged via NLog so you can");
            sb.AppendLine("// grab it from the Torch console or the output file.");
            sb.AppendLine("//");
            sb.AppendLine("// Live Streaming:  Call StartLcdStream() from a chat command (e.g.");
            sb.AppendLine("// /lcd watch) and the snippet will stream frames to the layout tool");
            sb.AppendLine("// over a named pipe for 60 seconds, then auto-disarm.  The code is");
            sb.AppendLine("// completely dormant and causes zero overhead when not streaming.");
            sb.AppendLine("//");
            sb.AppendLine("// Debug Variables:  Call SnapshotDebug(\"name\", value) before");
            sb.AppendLine("// SerializeSnapshot() to stream field values into the layout tool's");
            sb.AppendLine("// Variables tab for live debugging.");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System;");
            sb.AppendLine("//   using System.Collections.Generic;");
            sb.AppendLine("//   using System.IO;");
            sb.AppendLine("//   using System.IO.Pipes;");
            sb.AppendLine("//   using System.Text;");
            sb.AppendLine("//   using NLog;");
            sb.AppendLine("//   using Sandbox.ModAPI;");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;");
            sb.AppendLine("//   using VRageMath;");
            sb.AppendLine();
            sb.AppendLine("private static readonly Logger Log = LogManager.GetCurrentClassLogger();");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "public ");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Snapshots all sprites currently on a surface and writes them to a file.");
            sb.AppendLine("/// Call from a chat command handler, e.g.:");
            sb.AppendLine("///   var lcd = block as IMyTextSurfaceProvider;");
            sb.AppendLine("///   SnapshotLcd(lcd?.GetSurface(0), \"MyLcdSnapshot\");");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void SnapshotLcd(IMyTextSurface surface, string label = \"LcdSnapshot\")");
            sb.AppendLine("{");
            sb.AppendLine("    if (surface == null) { Log.Warn(\"SnapshotLcd: surface is null\"); return; }");
            sb.AppendLine();
            sb.AppendLine("    // NOTE: SE doesn't expose a way to read back an already-drawn frame.");
            sb.AppendLine("    // You need to collect sprites BEFORE adding them to the frame.");
            sb.AppendLine("    // Call SnapshotCollect(sprites) in your rendering code first.");
            sb.AppendLine("    if (_snapshotSprites.Count == 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn(\"SnapshotLcd: no sprites collected — call SnapshotCollect() first\");");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    string output = SerializeSnapshot();");
            sb.AppendLine("    string path = Path.Combine(");
            sb.AppendLine("        StoragePath ?? Directory.GetCurrentDirectory(),");
            sb.AppendLine("        $\"{label}_{DateTime.Now:yyyyMMdd_HHmmss}.cs\");");
            sb.AppendLine();
            sb.AppendLine("    File.WriteAllText(path, output);");
            sb.AppendLine("    Log.Info($\"LCD snapshot saved: {path}  ({_snapshotSprites.Count} sprites)\");");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Finds the first IMyTextSurfaceProvider block whose name or CustomData contains");
            sb.AppendLine("/// <paramref name=\"tag\"/> using a two-pass search that avoids grid-iteration false");
            sb.AppendLine("/// positives. Pass 1 checks CustomName only; Pass 2 checks CustomData only.");
            sb.AppendLine("/// This ensures a block named 'mylcd' is never returned ahead of the correct");
            sb.AppendLine("/// panel tagged 'SCREEN:Main' in its CustomData just because it appears first in");
            sb.AppendLine("/// the grid's block list.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("/// <param name=\"allBlocks\">All terminal blocks to search. Fetch once with");
            sb.AppendLine("///   GridTerminalSystem.GetBlocksOfType / GetBlocks and reuse.</param>");
            sb.AppendLine("/// <param name=\"tag\">Case-insensitive tag to search for.</param>");
            sb.AppendLine("/// <param name=\"foundName\">Receives the CustomName of the matched block, or null.</param>");
            sb.AppendLine("public IMyTextSurfaceProvider FindPanel(");
            sb.AppendLine("    List<IMyTerminalBlock> allBlocks, string tag, out string foundName)");
            sb.AppendLine("{");
            sb.AppendLine("    foundName = null;");
            sb.AppendLine("    // Pass 1: CustomName only — name always takes priority over CustomData tags");
            sb.AppendLine("    foreach (var b in allBlocks)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (b is IMyTextSurfaceProvider");
            sb.AppendLine("            && b.CustomName.IndexOf(tag, StringComparison.OrdinalIgnoreCase) >= 0)");
            sb.AppendLine("        { foundName = b.CustomName; return (IMyTextSurfaceProvider)b; }");
            sb.AppendLine("    }");
            sb.AppendLine("    // Pass 2: CustomData only — tag-based discovery fallback");
            sb.AppendLine("    foreach (var b in allBlocks)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (b is IMyTextSurfaceProvider");
            sb.AppendLine("            && b.CustomData.IndexOf(tag, StringComparison.OrdinalIgnoreCase) >= 0)");
            sb.AppendLine("        { foundName = b.CustomName; return (IMyTextSurfaceProvider)b; }");
            sb.AppendLine("    }");
            sb.AppendLine("    return null;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── Live LCD Streaming (self-disarming) ──────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("private NamedPipeClientStream _lcdPipe;");
            sb.AppendLine("private DateTime _lcdStreamExpiry;");
            sb.AppendLine("private bool _lcdStreamActive;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Starts streaming LCD snapshots to the layout tool over a named pipe.");
            sb.AppendLine("/// The stream auto-disarms after <paramref name=\"seconds\"/> (default 60).");
            sb.AppendLine("/// Call from a chat command, e.g. /lcd watch.");
            sb.AppendLine("/// The code is completely dormant when not streaming — zero overhead.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StartLcdStream(int seconds = 60)");
            sb.AppendLine("{");
            sb.AppendLine("    StopLcdStream();");
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        _lcdPipe = new NamedPipeClientStream(\".\", \"SELcdSnapshot\", PipeDirection.Out);");
            sb.AppendLine("        _lcdPipe.Connect(2000); // 2 s timeout — layout tool must be listening");
            sb.AppendLine("        _lcdStreamExpiry = DateTime.UtcNow.AddSeconds(seconds);");
            sb.AppendLine("        _lcdStreamActive = true;");
            sb.AppendLine("        Log.Info($\"LCD stream started — auto-disarms in {seconds}s\");");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD stream failed to connect: {ex.Message}\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Stops the live LCD stream immediately.</summary>");
            sb.AppendLine("public void StopLcdStream()");
            sb.AppendLine("{");
            sb.AppendLine("    _lcdStreamActive = false;");
            sb.AppendLine("    try { _lcdPipe?.Dispose(); } catch { }");
            sb.AppendLine("    _lcdPipe = null;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Sends the current snapshot frame over the pipe if streaming is active.");
            sb.AppendLine("/// Call this after SnapshotCollect() in your render loop.");
            sb.AppendLine("/// When the timer expires the stream self-disarms automatically.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StreamFrame()");
            sb.AppendLine("{");
            sb.AppendLine("    if (!_lcdStreamActive) return; // dormant — zero overhead");
            sb.AppendLine();
            sb.AppendLine("    // Auto-disarm check");
            sb.AppendLine("    if (DateTime.UtcNow > _lcdStreamExpiry)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Info(\"LCD stream expired — auto-disarmed\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    if (_snapshotSprites.Count == 0) return;");
            sb.AppendLine();
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        string frame = SerializeSnapshot();");
            sb.AppendLine("        byte[] payload = Encoding.UTF8.GetBytes(frame);");
            sb.AppendLine("        byte[] header = BitConverter.GetBytes(payload.Length);");
            sb.AppendLine("        _lcdPipe.Write(header, 0, 4);");
            sb.AppendLine("        _lcdPipe.Write(payload, 0, payload.Length);");
            sb.AppendLine("        _lcdPipe.Flush();");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD stream write failed: {ex.Message}\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── File-Based Live Streaming (alternative to named pipes) ───────────");
            sb.AppendLine("// Use this when the layout tool is on the same machine as the server.");
            sb.AppendLine("// The layout tool watches the file via Edit → Watch Snapshot File…");
            sb.AppendLine();
            sb.AppendLine("private string _lcdStreamFilePath;");
            sb.AppendLine("private DateTime _lcdFileStreamExpiry;");
            sb.AppendLine("private bool _lcdFileStreamActive;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Starts writing LCD snapshots to a file on disk at the given path.");
            sb.AppendLine("/// The stream auto-disarms after <paramref name=\"seconds\"/> (default 60).");
            sb.AppendLine("/// Point the layout tool's \"Watch Snapshot File\" at this path.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StartLcdFileStream(string filePath, int seconds = 60)");
            sb.AppendLine("{");
            sb.AppendLine("    StopLcdFileStream();");
            sb.AppendLine("    _lcdStreamFilePath = filePath;");
            sb.AppendLine("    _lcdFileStreamExpiry = DateTime.UtcNow.AddSeconds(seconds);");
            sb.AppendLine("    _lcdFileStreamActive = true;");
            sb.AppendLine("    Log.Info($\"LCD file stream started → {filePath}  (auto-disarms in {seconds}s)\");");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Stops the file-based LCD stream immediately.</summary>");
            sb.AppendLine("public void StopLcdFileStream()");
            sb.AppendLine("{");
            sb.AppendLine("    _lcdFileStreamActive = false;");
            sb.AppendLine("    _lcdStreamFilePath = null;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Writes the current snapshot to the stream file if file streaming is active.");
            sb.AppendLine("/// Call this after SnapshotCollect() in your render loop.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StreamFrameToFile()");
            sb.AppendLine("{");
            sb.AppendLine("    if (!_lcdFileStreamActive) return; // dormant — zero overhead");
            sb.AppendLine();
            sb.AppendLine("    if (DateTime.UtcNow > _lcdFileStreamExpiry)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Info(\"LCD file stream expired — auto-disarmed\");");
            sb.AppendLine("        StopLcdFileStream();");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    if (_snapshotSprites.Count == 0) return;");
            sb.AppendLine();
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        File.WriteAllText(_lcdStreamFilePath, SerializeSnapshot());");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD file stream write failed: {ex.Message}\");");
            sb.AppendLine("        StopLcdFileStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string GenerateSnapshotHelper_Pulsar()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// ─── LCD Snapshot Helper (Pulsar Plugin) ─────────────────────────────");
            sb.AppendLine("// Add this to your IPlugin class.  Wire up SnapshotLcd() to a chat");
            sb.AppendLine("// command or call it from your Update() loop.");
            sb.AppendLine("//");
            sb.AppendLine("// The snapshot is written to a file and logged via NLog so you can");
            sb.AppendLine("// grab it from the Pulsar console or the output file.");
            sb.AppendLine("//");
            sb.AppendLine("// Live Streaming:  Call StartLcdStream() from a command and the snippet");
            sb.AppendLine("// will stream frames to the layout tool over a named pipe for 60 seconds,");
            sb.AppendLine("// then auto-disarm.  The code is completely dormant and causes zero");
            sb.AppendLine("// overhead when not streaming.");
            sb.AppendLine("//");
            sb.AppendLine("// Debug Variables:  Call SnapshotDebug(\"name\", value) before");
            sb.AppendLine("// SerializeSnapshot() to stream field values into the layout tool's");
            sb.AppendLine("// Variables tab for live debugging.");
            sb.AppendLine("//");
            sb.AppendLine("// Surface access (Pulsar — no GridTerminalSystem):");
            sb.AppendLine("//   foreach (MyEntity e in MyEntities.GetEntities())");
            sb.AppendLine("//   {");
            sb.AppendLine("//       var grid = e as MyCubeGrid;");
            sb.AppendLine("//       if (grid == null) continue;");
            sb.AppendLine("//       foreach (var slim in grid.CubeBlocks)");
            sb.AppendLine("//       {");
            sb.AppendLine("//           var panel = slim.FatBlock as IMyTextPanel;");
            sb.AppendLine("//           if (panel != null && panel.CustomName == \"YourLCD\")");
            sb.AppendLine("//               surface = panel;");
            sb.AppendLine("//       }");
            sb.AppendLine("//   }");
            sb.AppendLine("// ───────────────────────────────────────────────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System;");
            sb.AppendLine("//   using System.Collections.Generic;");
            sb.AppendLine("//   using System.IO;");
            sb.AppendLine("//   using System.IO.Pipes;");
            sb.AppendLine("//   using System.Text;");
            sb.AppendLine("//   using NLog;");
            sb.AppendLine("//   using Sandbox.Game.Entities;       // MyCubeGrid, MyEntities");
            sb.AppendLine("//   using Sandbox.ModAPI;               // IMyTextPanel");
            sb.AppendLine("//   using VRage.Game.Entity;            // MyEntity");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;     // MySprite, SpriteType, ContentType");
            sb.AppendLine("//   using VRage.Plugins;                // IPlugin");
            sb.AppendLine("//   using VRageMath;                    // Vector2, Color");
            sb.AppendLine();
            sb.AppendLine("private static readonly Logger Log = LogManager.GetCurrentClassLogger();");
            sb.AppendLine();
            AppendSnapshotCore(sb, accessModifier: "public ");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Snapshots all sprites currently collected and writes them to a file.");
            sb.AppendLine("/// Call SnapshotCollect(sprites) in your Update() rendering code first,");
            sb.AppendLine("/// then trigger this via a command or one-shot flag.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void SnapshotLcd(string label = \"LcdSnapshot\")");
            sb.AppendLine("{");
            sb.AppendLine("    if (_snapshotSprites.Count == 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn(\"SnapshotLcd: no sprites collected — call SnapshotCollect() first\");");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    string output = SerializeSnapshot();");
            sb.AppendLine("    string dir = Directory.GetCurrentDirectory();");
            sb.AppendLine("    string path = Path.Combine(dir, $\"{label}_{DateTime.Now:yyyyMMdd_HHmmss}.cs\");");
            sb.AppendLine();
            sb.AppendLine("    File.WriteAllText(path, output);");
            sb.AppendLine("    Log.Info($\"LCD snapshot saved: {path}  ({_snapshotSprites.Count} sprites)\");");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── Live LCD Streaming (self-disarming) ──────────────────────────────");
            sb.AppendLine();
            sb.AppendLine("private NamedPipeClientStream _lcdPipe;");
            sb.AppendLine("private DateTime _lcdStreamExpiry;");
            sb.AppendLine("private bool _lcdStreamActive;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Starts streaming LCD snapshots to the layout tool over a named pipe.");
            sb.AppendLine("/// The stream auto-disarms after <paramref name=\"seconds\"/> (default 60).");
            sb.AppendLine("/// The code is completely dormant when not streaming — zero overhead.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StartLcdStream(int seconds = 60)");
            sb.AppendLine("{");
            sb.AppendLine("    StopLcdStream();");
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        _lcdPipe = new NamedPipeClientStream(\".\", \"SELcdSnapshot\", PipeDirection.Out);");
            sb.AppendLine("        _lcdPipe.Connect(2000); // 2 s timeout — layout tool must be listening");
            sb.AppendLine("        _lcdStreamExpiry = DateTime.UtcNow.AddSeconds(seconds);");
            sb.AppendLine("        _lcdStreamActive = true;");
            sb.AppendLine("        Log.Info($\"LCD stream started — auto-disarms in {seconds}s\");");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD stream failed to connect: {ex.Message}\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Stops the live LCD stream immediately.</summary>");
            sb.AppendLine("public void StopLcdStream()");
            sb.AppendLine("{");
            sb.AppendLine("    _lcdStreamActive = false;");
            sb.AppendLine("    try { _lcdPipe?.Dispose(); } catch { }");
            sb.AppendLine("    _lcdPipe = null;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Sends the current snapshot frame over the pipe if streaming is active.");
            sb.AppendLine("/// Call this after SnapshotCollect() in your Update() loop.");
            sb.AppendLine("/// When the timer expires the stream self-disarms automatically.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StreamFrame()");
            sb.AppendLine("{");
            sb.AppendLine("    if (!_lcdStreamActive) return; // dormant — zero overhead");
            sb.AppendLine();
            sb.AppendLine("    // Auto-disarm check");
            sb.AppendLine("    if (DateTime.UtcNow > _lcdStreamExpiry)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Info(\"LCD stream expired — auto-disarmed\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    if (_snapshotSprites.Count == 0) return;");
            sb.AppendLine();
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        string frame = SerializeSnapshot();");
            sb.AppendLine("        byte[] payload = Encoding.UTF8.GetBytes(frame);");
            sb.AppendLine("        byte[] header = BitConverter.GetBytes(payload.Length);");
            sb.AppendLine("        _lcdPipe.Write(header, 0, 4);");
            sb.AppendLine("        _lcdPipe.Write(payload, 0, payload.Length);");
            sb.AppendLine("        _lcdPipe.Flush();");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD stream write failed: {ex.Message}\");");
            sb.AppendLine("        StopLcdStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("// ── File-Based Live Streaming (alternative to named pipes) ───────────");
            sb.AppendLine("// Use this when the layout tool is on the same machine as the server.");
            sb.AppendLine("// The layout tool watches the file via Edit → Watch Snapshot File…");
            sb.AppendLine();
            sb.AppendLine("private string _lcdStreamFilePath;");
            sb.AppendLine("private DateTime _lcdFileStreamExpiry;");
            sb.AppendLine("private bool _lcdFileStreamActive;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Starts writing LCD snapshots to a file on disk at the given path.");
            sb.AppendLine("/// The stream auto-disarms after <paramref name=\"seconds\"/> (default 60).");
            sb.AppendLine("/// Point the layout tool's \"Watch Snapshot File\" at this path.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StartLcdFileStream(string filePath, int seconds = 60)");
            sb.AppendLine("{");
            sb.AppendLine("    StopLcdFileStream();");
            sb.AppendLine("    _lcdStreamFilePath = filePath;");
            sb.AppendLine("    _lcdFileStreamExpiry = DateTime.UtcNow.AddSeconds(seconds);");
            sb.AppendLine("    _lcdFileStreamActive = true;");
            sb.AppendLine("    Log.Info($\"LCD file stream started → {filePath}  (auto-disarms in {seconds}s)\");");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Stops the file-based LCD stream immediately.</summary>");
            sb.AppendLine("public void StopLcdFileStream()");
            sb.AppendLine("{");
            sb.AppendLine("    _lcdFileStreamActive = false;");
            sb.AppendLine("    _lcdStreamFilePath = null;");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Writes the current snapshot to the stream file if file streaming is active.");
            sb.AppendLine("/// Call this after SnapshotCollect() in your Update() loop.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public void StreamFrameToFile()");
            sb.AppendLine("{");
            sb.AppendLine("    if (!_lcdFileStreamActive) return; // dormant — zero overhead");
            sb.AppendLine();
            sb.AppendLine("    if (DateTime.UtcNow > _lcdFileStreamExpiry)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Info(\"LCD file stream expired — auto-disarmed\");");
            sb.AppendLine("        StopLcdFileStream();");
            sb.AppendLine("        return;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    if (_snapshotSprites.Count == 0) return;");
            sb.AppendLine();
            sb.AppendLine("    try");
            sb.AppendLine("    {");
            sb.AppendLine("        File.WriteAllText(_lcdStreamFilePath, SerializeSnapshot());");
            sb.AppendLine("    }");
            sb.AppendLine("    catch (Exception ex)");
            sb.AppendLine("    {");
            sb.AppendLine("        Log.Warn($\"LCD file stream write failed: {ex.Message}\");");
            sb.AppendLine("        StopLcdFileStream();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>
        /// Appends the shared SnapshotCollect + SerializeSnapshot methods.
        /// </summary>
        private static void AppendSnapshotCore(StringBuilder sb, string accessModifier)
        {
            // The snapshot collector list
            sb.AppendLine($"{accessModifier}List<MySprite> _snapshotSprites = new List<MySprite>();");
            sb.AppendLine();

            // Row data collector — captures the LcdSpriteRow[] that drove rendering
            sb.AppendLine($"{accessModifier}List<LcdSpriteRow> _snapshotRows = new List<LcdSpriteRow>();");
            sb.AppendLine();

            // Snapshot tag — set this to identify which plugin/script produced the snapshot
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Set this to a unique label (e.g. \"MyPulsarHUD\") so the layout tool");
            sb.AppendLine("/// can distinguish snapshots from different plugins on the same LCD.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}string _snapshotTag = \"\";");
            sb.AppendLine();

            // ── Per-sprite incremental collection ────────────────────────────
            // Use SnapshotBegin() + SnapshotAdd() when sprites are built across
            // multiple render phases (e.g. text in one pass, bars/icons in another).
            // This ensures ALL sprites are captured regardless of which phase adds them.
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Starts a new snapshot frame.  Clears previously collected sprites and rows.");
            sb.AppendLine("/// Call once at the TOP of your render method, before any SnapshotAdd calls.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotBegin()");
            sb.AppendLine("{");
            sb.AppendLine("    _snapshotSprites.Clear();");
            sb.AppendLine("    _snapshotRows.Clear();");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Adds a single sprite to the snapshot.  Call this alongside every frame.Add()");
            sb.AppendLine("/// so the snapshot captures ALL sprites — text, bars, icons, separators, etc.");
            sb.AppendLine("/// <para>Usage:  frame.Add(sprite);  SnapshotAdd(sprite);</para>");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotAdd(MySprite sprite)");
            sb.AppendLine("{");
            sb.AppendLine("    _snapshotSprites.Add(sprite);");
            sb.AppendLine("}");
            sb.AppendLine();

            // Bulk collect sprites — for code that builds a complete list before drawing
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Bulk-collects ALL sprites at once.  Use this when you have a single");
            sb.AppendLine("/// List&lt;MySprite&gt; that already contains every sprite (text, bars, icons).");
            sb.AppendLine("/// If your rendering adds sprites in multiple passes, prefer");
            sb.AppendLine("/// SnapshotBegin() + SnapshotAdd() instead so nothing is missed.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotCollect(List<MySprite> sprites)");
            sb.AppendLine("{");
            sb.AppendLine("    _snapshotSprites.Clear();");
            sb.AppendLine("    _snapshotSprites.AddRange(sprites);");
            sb.AppendLine("}");
            sb.AppendLine();

            // Collect row data — call this alongside SnapshotCollect so the layout tool
            // can use real game data instead of placeholder values.
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Captures the LcdSpriteRow data that drove rendering so the layout");
            sb.AppendLine("/// tool can use real game values (item names, amounts, bar fills) instead");
            sb.AppendLine("/// of placeholder text.  Call this right before or after SnapshotCollect.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotCollectRows(LcdSpriteRow[] rows)");
            sb.AppendLine("{");
            sb.AppendLine("    _snapshotRows.Clear();");
            sb.AppendLine("    if (rows != null)");
            sb.AppendLine("        _snapshotRows.AddRange(rows);");
            sb.AppendLine("}");
            sb.AppendLine();

            // ── Debug Variables ──────────────────────────────────────────────
            // Plugin developers can stream arbitrary diagnostic state alongside
            // the sprite data so it appears in the layout tool's Variables tab.
            sb.AppendLine($"{accessModifier}Dictionary<string, object> _debugVars = new Dictionary<string, object>();");
            sb.AppendLine();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Records a named debug variable that will be sent to the layout tool");
            sb.AppendLine("/// alongside the sprite snapshot.  Call this for any field or computed value");
            sb.AppendLine("/// you want to inspect in the editor's Variables tab while live-streaming.");
            sb.AppendLine("/// <para>Example:  SnapshotDebug(\"_itemCount\", _itemCount);</para>");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}void SnapshotDebug(string name, object value)");
            sb.AppendLine("{");
            sb.AppendLine("    _debugVars[name] = value;");
            sb.AppendLine("}");
            sb.AppendLine();

            // Serializer
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Serializes collected sprites AND row data into a snapshot that the");
            sb.AppendLine("/// layout tool can import.  Sprites become MySprite initializer code;");
            sb.AppendLine("/// rows are appended as @ROW comments so the tool can replay them.");
            sb.AppendLine("/// Paste the output into the layout tool's \"Paste Layout\" dialog.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"{accessModifier}string SerializeSnapshot()");
            sb.AppendLine("{");
            sb.AppendLine("    var sb = new StringBuilder();");
            sb.AppendLine("    sb.AppendLine(\"// ── LCD Snapshot ──\");");
            sb.AppendLine("    sb.AppendLine($\"// Captured: {DateTime.Now:yyyy-MM-dd HH:mm}  |  Sprites: {_snapshotSprites.Count}  |  Rows: {_snapshotRows.Count}\");");
            sb.AppendLine("    if (!string.IsNullOrEmpty(_snapshotTag))");
            sb.AppendLine("        sb.AppendLine($\"// @SnapshotTag: {_snapshotTag}\");");
            sb.AppendLine("    sb.AppendLine();");
            sb.AppendLine("    for (int i = 0; i < _snapshotSprites.Count; i++)");
            sb.AppendLine("    {");
            sb.AppendLine("        var s = _snapshotSprites[i];");
            sb.AppendLine("        sb.AppendLine(\"frame.Add(new MySprite\");");
            sb.AppendLine("        sb.AppendLine(\"{\");");
            sb.AppendLine("        sb.AppendLine($\"    Type           = SpriteType.{s.Type},\");");
            sb.AppendLine("        sb.AppendLine($\"    Data           = \\\"{s.Data}\\\",\");");
            sb.AppendLine("        if (s.Position.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Position       = new Vector2({s.Position.Value.X:F1}f, {s.Position.Value.Y:F1}f),\");");
            sb.AppendLine("        if (s.Size.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Size           = new Vector2({s.Size.Value.X:F1}f, {s.Size.Value.Y:F1}f),\");");
            sb.AppendLine("        if (s.Color.HasValue)");
            sb.AppendLine("            sb.AppendLine($\"    Color          = new Color({s.Color.Value.R}, {s.Color.Value.G}, {s.Color.Value.B}, {s.Color.Value.A}),\");");
            sb.AppendLine("        if (s.FontId != null)");
            sb.AppendLine("            sb.AppendLine($\"    FontId         = \\\"{s.FontId}\\\",\");");
            sb.AppendLine("        sb.AppendLine($\"    Alignment      = TextAlignment.{s.Alignment},\");");
            sb.AppendLine("        sb.AppendLine($\"    RotationOrScale = {s.RotationOrScale:F4}f,\");");
            sb.AppendLine("        sb.AppendLine(\"});\");");
            sb.AppendLine("        sb.AppendLine();");
            sb.AppendLine("    }");
            sb.AppendLine();
            // Row data section — encoded as comments so it survives paste workflows
            sb.AppendLine("    // Serialize captured row data");
            sb.AppendLine("    if (_snapshotRows.Count > 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        sb.AppendLine();");
            sb.AppendLine("        sb.AppendLine(\"// ── Captured Row Data ──\");");
            sb.AppendLine("        sb.AppendLine(\"// The layout tool uses these to replay render methods with real game values.\");");
            sb.AppendLine("        sb.AppendLine(\"// Format: @ROW:Kind|Text|StatText|IconSprite|R,G,B,A|BarFill|R,G,B,A|ShowAlert\");");
            sb.AppendLine("        foreach (var r in _snapshotRows)");
            sb.AppendLine("        {");
            sb.AppendLine("            string text     = (r.Text ?? \"\").Replace(\"|\", \"\\\\|\");");
            sb.AppendLine("            string statText = (r.StatText ?? \"\").Replace(\"|\", \"\\\\|\");");
            sb.AppendLine("            string icon     = (r.IconSprite ?? \"\").Replace(\"|\", \"\\\\|\");");
            sb.AppendLine("            string tc       = $\"{r.TextColor.R},{r.TextColor.G},{r.TextColor.B},{r.TextColor.A}\";");
            sb.AppendLine("            string bf       = r.BarFill.ToString(\"F4\");");
            sb.AppendLine("            string bfc      = $\"{r.BarFillColor.R},{r.BarFillColor.G},{r.BarFillColor.B},{r.BarFillColor.A}\";");
            sb.AppendLine("            string alert    = r.ShowAlert ? \"1\" : \"0\";");
            sb.AppendLine("            sb.AppendLine($\"// @ROW:{r.RowKind}|{text}|{statText}|{icon}|{tc}|{bf}|{bfc}|{alert}\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Debug variables section — encoded as comments alongside row/sprite data
            sb.AppendLine("    // Serialize debug variables");
            sb.AppendLine("    if (_debugVars.Count > 0)");
            sb.AppendLine("    {");
            sb.AppendLine("        sb.AppendLine();");
            sb.AppendLine("        sb.AppendLine(\"// ── Debug Variables ──\");");
            sb.AppendLine("        sb.AppendLine(\"// Format: @DebugVar: name (Type) = value\");");
            sb.AppendLine("        foreach (var kv in _debugVars)");
            sb.AppendLine("        {");
            sb.AppendLine("            string typeName = kv.Value != null ? kv.Value.GetType().Name : \"Null\";");
            sb.AppendLine("            string val = kv.Value != null ? kv.Value.ToString() : \"(null)\";");
            sb.AppendLine("            if (kv.Value is string) val = \"\\\"\" + val + \"\\\"\";");
            sb.AppendLine("            if (kv.Value is float f) val = f.ToString(\"F4\");");
            sb.AppendLine("            if (kv.Value is double d) val = d.ToString(\"F4\");");
            sb.AppendLine("            sb.AppendLine($\"// @DebugVar: {kv.Key} ({typeName}) = {val}\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    return sb.ToString();");
            sb.AppendLine("}");
        }
        /// <summary>
        /// Escapes a string for a C# string literal, turning any PUA or non-ASCII
        /// character into a \uXXXX escape so the generated code is always ASCII-safe.
        /// </summary>
        private static string Esc(string s)
        {
            if (s == null) return "";
            var sb = new StringBuilder(s.Length * 2);
            foreach (char c in s)
            {
                if (c == '\\') { sb.Append("\\\\"); }
                else if (c == '"') { sb.Append("\\\""); }
                else if (c >= 0x007F)  // non-ASCII or PUA → \uXXXX
                    sb.Append($"\\u{(int)c:X4}");
                else
                    sb.Append(c);
            }
            return sb.ToString();
        }

    }
}
