using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using SESpriteLCDLayoutTool.Models;
using SESpriteLCDLayoutTool.Models.Rig;

namespace SESpriteLCDLayoutTool.Services
{
    /// <summary>
    /// Phase B runtime code generator for 2D rig animation.
    /// Produces a self-contained, paste-ready C# block that contains:
    ///   • baked rig data (origin, bones, bindings, clip keyframes)
    ///   • a small runtime sampler/evaluator that mirrors <see cref="RigClipSampler"/>
    ///     and <see cref="RigEvaluator"/> exactly, with no external references
    ///   • a DrawRig(IMyTextSurface, float time) method that draws every bound
    ///     sprite at its animated pose plus every unbound sprite at its rest pose
    ///
    /// The output uses only Sandbox.ModAPI / VRage.Game.GUI.TextPanel / VRageMath types
    /// so it pastes into PB scripts, mods, plugins, or Pulsar plugins unchanged.
    /// Unbound sprites are emitted at their literal layout positions (same shape
    /// the regular <see cref="CodeGenerator"/> emits) so the result matches the
    /// editor preview when <c>time = 0</c>.
    /// </summary>
    public static class RigCodeGenerator
    {
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        /// <summary>
        /// Generates a complete runtime rig+animation snippet for the first enabled
        /// rig on the layout. Returns a comment-only stub if there is no rig.
        /// </summary>
        public static string Generate(LcdLayout layout, string methodName = "DrawRig", string surfaceParam = "surface")
        {
            if (layout == null) throw new ArgumentNullException(nameof(layout));
            var rig = PickRig(layout);
            var sb = new StringBuilder();

            sb.AppendLine("// ─── Generated by SE Sprite LCD Layout Tool — Rig Runtime ───");
            sb.AppendLine($"// Generated: {DateTime.Now:yyyy-MM-dd HH:mm}");
            sb.AppendLine("// Required usings:");
            sb.AppendLine("//   using System.Collections.Generic;");
            sb.AppendLine("//   using VRage.Game.GUI.TextPanel;   // MySprite, SpriteType, ContentType");
            sb.AppendLine("//   using VRageMath;                  // Vector2, Color");
            sb.AppendLine("//   using Sandbox.ModAPI;             // IMyTextSurface  (or Sandbox.ModAPI.Ingame for PB)");
            sb.AppendLine("//");
            sb.AppendLine($"// Call {methodName}({surfaceParam}, t) every tick where t advances in seconds.");
            sb.AppendLine("// — OR — call AddRigSprites(frame, _rigTime); from inside an existing");
            sb.AppendLine("// using(var frame = surface.DrawFrame()) block to compose with static sprites.");
            sb.AppendLine("// _rigTime is wall-clock-derived, so playback is identical whether the host");
            sb.AppendLine("// calls render once per tick or only intermittently (e.g. editor preview).");
            sb.AppendLine();

            if (rig == null || rig.Bones == null || rig.Bones.Count == 0)
            {
                sb.AppendLine("// No rig present on this layout — nothing to emit.");
                sb.AppendLine($"public void {methodName}(IMyTextSurface {surfaceParam}, float time) {{ }}");
                return sb.ToString();
            }

            EmitDataTypes(sb);
            EmitDataLiterals(sb, layout, rig);
            EmitSamplerAndEvaluator(sb);
            EmitTimeField(sb);
            EmitAddRigSpritesMethod(sb, layout, rig);
            EmitDrawMethod(sb, layout, rig, methodName, surfaceParam);

            return sb.ToString();
        }

        /// <summary>
        /// Returns the GUIDs (<see cref="SpriteEntry.Id"/>) of every sprite that the
        /// active rig binds to a bone. Used by <see cref="RigCodeInjector"/> to mute
        /// the corresponding static <c>frame.Add(...)</c> blocks so they don't double-render.
        /// </summary>
        public static System.Collections.Generic.HashSet<string> GetBoundSpriteIds(LcdLayout layout)
        {
            var result = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);
            if (layout == null) return result;
            var rig = PickRig(layout);
            if (rig == null || rig.Bindings == null || layout.Sprites == null) return result;
            foreach (var bd in rig.Bindings)
            {
                if (bd == null || bd.Muted || bd.SpriteIndex < 0 || bd.SpriteIndex >= layout.Sprites.Count) continue;
                var sp = layout.Sprites[bd.SpriteIndex];
                if (sp != null && !string.IsNullOrEmpty(sp.Id)) result.Add(sp.Id);
            }
            return result;
        }

        private static Rig PickRig(LcdLayout layout)
        {
            if (layout.Rigs == null) return null;
            foreach (var r in layout.Rigs)
                if (r != null && r.Enabled && r.Bones != null && r.Bones.Count > 0) return r;
            // Fall back to the first rig even if disabled, so the user still sees output.
            foreach (var r in layout.Rigs) if (r != null) return r;
            return null;
        }

        // ─────────────────────────────────────────────────────────────────────
        // Emitters
        // ─────────────────────────────────────────────────────────────────────

        private static void EmitDataTypes(StringBuilder sb)
        {
            sb.AppendLine("// ── Baked rig data types ─────────────────────────────────────");
            sb.AppendLine("private struct RigBoneData {");
            sb.AppendLine("    public int ParentIndex; // -1 for root");
            sb.AppendLine("    public float LocalX, LocalY, LocalRot, LocalSx, LocalSy;");
            sb.AppendLine("}");
            sb.AppendLine("private struct RigBindingData {");
            sb.AppendLine("    public int BoneIndex;");
            sb.AppendLine("    public int SpriteIndex;");
            sb.AppendLine("    public float OffX, OffY, RotOff, Sx, Sy;");
            sb.AppendLine("}");
            sb.AppendLine("private struct RigKey {");
            sb.AppendLine("    public float T;");
            sb.AppendLine("    public float LocalX, LocalY, LocalRot, LocalSx, LocalSy;");
            sb.AppendLine("    public int Easing; // 0=linear, 1=easeInOut, 2=step");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitDataLiterals(StringBuilder sb, LcdLayout layout, Rig rig)
        {
            // Stable bone index map.
            var boneIndex = new Dictionary<string, int>(rig.Bones.Count);
            for (int i = 0; i < rig.Bones.Count; i++)
                if (rig.Bones[i] != null && !string.IsNullOrEmpty(rig.Bones[i].Id))
                    boneIndex[rig.Bones[i].Id] = i;

            sb.AppendLine("// ── Baked rig data ───────────────────────────────────────────");
            sb.AppendLine($"private const float RigOriginX = {F(rig.OriginX)};");
            sb.AppendLine($"private const float RigOriginY = {F(rig.OriginY)};");
            sb.AppendLine();

            sb.AppendLine("private static readonly RigBoneData[] RigBones = new RigBoneData[] {");
            for (int i = 0; i < rig.Bones.Count; i++)
            {
                var b = rig.Bones[i];
                if (b == null) { sb.AppendLine("    new RigBoneData { ParentIndex = -1 },"); continue; }
                int parent = -1;
                if (!string.IsNullOrEmpty(b.ParentId)) boneIndex.TryGetValue(b.ParentId, out parent);
                if (parent == i) parent = -1; // self-parent guard
                sb.AppendLine($"    new RigBoneData {{ ParentIndex = {parent}, LocalX = {F(b.LocalX)}, LocalY = {F(b.LocalY)}, LocalRot = {F(b.LocalRotation)}, LocalSx = {F(b.LocalScaleX)}, LocalSy = {F(b.LocalScaleY)} }}, // [{i}] {Esc(b.Name)}");
            }
            sb.AppendLine("};");
            sb.AppendLine();

            sb.AppendLine("private static readonly RigBindingData[] RigBindings = new RigBindingData[] {");
            int spriteCount = layout.Sprites != null ? layout.Sprites.Count : 0;
            if (rig.Bindings != null)
            {
                foreach (var bd in rig.Bindings)
                {
                    if (bd == null || bd.Muted) continue;
                    if (bd.SpriteIndex < 0 || bd.SpriteIndex >= spriteCount) continue;
                    int bi;
                    if (string.IsNullOrEmpty(bd.BoneId) || !boneIndex.TryGetValue(bd.BoneId, out bi)) continue;
                    sb.AppendLine($"    new RigBindingData {{ BoneIndex = {bi}, SpriteIndex = {bd.SpriteIndex}, OffX = {F(bd.OffsetX)}, OffY = {F(bd.OffsetY)}, RotOff = {F(bd.RotationOffset)}, Sx = {F(bd.ScaleX)}, Sy = {F(bd.ScaleY)} }},");
                }
            }
            sb.AppendLine("};");
            sb.AppendLine();

            // Clip — pick active or first.
            RigClip clip = null;
            if (rig.Clips != null)
            {
                if (!string.IsNullOrEmpty(rig.ActiveClipId))
                    clip = rig.Clips.Find(c => c != null && c.Id == rig.ActiveClipId);
                if (clip == null && rig.Clips.Count > 0) clip = rig.Clips[0];
            }
            float duration = clip != null ? Math.Max(0.0001f, clip.Duration) : 1f;
            bool loop = clip != null ? clip.Loop : true;
            // Use static readonly (not const) so the C# compiler can't fold these
            // values into surrounding branches. With const, the loop/clamp arms in
            // RigEvaluate become unreachable from one side and the in-game PB
            // editor (and Roslyn) emit "Unreachable code detected" warnings.
            sb.AppendLine($"private static readonly float RigClipDuration = {F(duration)};");
            sb.AppendLine($"private static readonly bool  RigClipLoop = {(loop ? "true" : "false")};");
            sb.AppendLine();

            // One key array per bone (parallel to RigBones), empty arrays for bones with no track.
            sb.AppendLine("private static readonly RigKey[][] RigClipTracks = new RigKey[][] {");
            for (int i = 0; i < rig.Bones.Count; i++)
            {
                var b = rig.Bones[i];
                RigBoneTrack track = null;
                if (clip != null && b != null && !string.IsNullOrEmpty(b.Id))
                    track = clip.Tracks?.Find(t => t != null && t.BoneId == b.Id);
                if (track == null || track.Keys == null || track.Keys.Count == 0)
                {
                    sb.AppendLine("    new RigKey[0],");
                    continue;
                }
                var keys = track.Keys.FindAll(k => k != null);
                keys.Sort((a, b2) => a.Time.CompareTo(b2.Time));
                sb.AppendLine("    new RigKey[] {");
                foreach (var k in keys)
                    sb.AppendLine($"        new RigKey {{ T = {F(k.Time)}, LocalX = {F(k.LocalX)}, LocalY = {F(k.LocalY)}, LocalRot = {F(k.LocalRotation)}, LocalSx = {F(k.LocalScaleX)}, LocalSy = {F(k.LocalScaleY)}, Easing = {(int)k.Easing} }},");
                sb.AppendLine($"    }}, // [{i}] {Esc(b?.Name)}");
            }
            sb.AppendLine("};");
            sb.AppendLine();
        }

        private static void EmitSamplerAndEvaluator(StringBuilder sb)
        {
            sb.AppendLine("// ── Runtime sampler + evaluator (mirrors editor) ─────────────");
            sb.AppendLine("private static float RigEase(float u, int easing) {");
            sb.AppendLine("    if (u < 0f) u = 0f; else if (u > 1f) u = 1f;");
            sb.AppendLine("    if (easing == 2) return 0f;             // step: hold first key");
            sb.AppendLine("    if (easing == 1) return u * u * (3f - 2f * u); // smoothstep");
            sb.AppendLine("    return u;                               // linear");
            sb.AppendLine("}");
            sb.AppendLine("private static float RigLerpAngle(float a, float b, float t) {");
            sb.AppendLine("    float d = b - a; const float PI = (float)System.Math.PI;");
            sb.AppendLine("    while (d >  PI) d -= 2f * PI;");
            sb.AppendLine("    while (d < -PI) d += 2f * PI;");
            sb.AppendLine("    return a + d * t;");
            sb.AppendLine("}");
            sb.AppendLine("private static void RigSampleTrack(RigKey[] keys, float time,");
            sb.AppendLine("    out float lx, out float ly, out float lr, out float lsx, out float lsy, out bool has) {");
            sb.AppendLine("    lx = ly = lr = 0f; lsx = lsy = 1f; has = false;");
            sb.AppendLine("    if (keys == null || keys.Length == 0) return;");
            sb.AppendLine("    has = true;");
            sb.AppendLine("    if (keys.Length == 1 || time <= keys[0].T) {");
            sb.AppendLine("        var k0 = keys[0]; lx = k0.LocalX; ly = k0.LocalY; lr = k0.LocalRot; lsx = k0.LocalSx; lsy = k0.LocalSy; return;");
            sb.AppendLine("    }");
            sb.AppendLine("    var last = keys[keys.Length - 1];");
            sb.AppendLine("    if (time >= last.T) { lx = last.LocalX; ly = last.LocalY; lr = last.LocalRot; lsx = last.LocalSx; lsy = last.LocalSy; return; }");
            sb.AppendLine("    int i = 0; while (i < keys.Length - 1 && keys[i + 1].T <= time) i++;");
            sb.AppendLine("    var a = keys[i]; var b = keys[i + 1];");
            sb.AppendLine("    float span = b.T - a.T; float u = span > 0f ? (time - a.T) / span : 0f;");
            sb.AppendLine("    u = RigEase(u, a.Easing);");
            sb.AppendLine("    lx  = a.LocalX  + (b.LocalX  - a.LocalX ) * u;");
            sb.AppendLine("    ly  = a.LocalY  + (b.LocalY  - a.LocalY ) * u;");
            sb.AppendLine("    lr  = RigLerpAngle(a.LocalRot, b.LocalRot, u);");
            sb.AppendLine("    lsx = a.LocalSx + (b.LocalSx - a.LocalSx) * u;");
            sb.AppendLine("    lsy = a.LocalSy + (b.LocalSy - a.LocalSy) * u;");
            sb.AppendLine("}");
            sb.AppendLine("private struct RigXform { public float X, Y, R, Sx, Sy; }");
            sb.AppendLine("private static RigXform RigCompose(RigXform p, float lx, float ly, float lr, float lsx, float lsy) {");
            sb.AppendLine("    float c = (float)System.Math.Cos(p.R), s = (float)System.Math.Sin(p.R);");
            sb.AppendLine("    RigXform o;");
            sb.AppendLine("    o.X  = p.X + (lx * p.Sx) * c - (ly * p.Sy) * s;");
            sb.AppendLine("    o.Y  = p.Y + (lx * p.Sx) * s + (ly * p.Sy) * c;");
            sb.AppendLine("    o.R  = p.R + lr;");
            sb.AppendLine("    o.Sx = p.Sx * lsx;");
            sb.AppendLine("    o.Sy = p.Sy * lsy;");
            sb.AppendLine("    return o;");
            sb.AppendLine("}");
            sb.AppendLine("private static void RigEvaluate(float time, RigXform[] outBones) {");
            sb.AppendLine("    float clipT = time;");
            sb.AppendLine("    if (RigClipDuration > 0f) {");
            sb.AppendLine("        if (RigClipLoop) { clipT = clipT % RigClipDuration; if (clipT < 0f) clipT += RigClipDuration; }");
            sb.AppendLine("        else if (clipT < 0f) clipT = 0f; else if (clipT > RigClipDuration) clipT = RigClipDuration;");
            sb.AppendLine("    }");
            sb.AppendLine("    RigXform origin; origin.X = RigOriginX; origin.Y = RigOriginY; origin.R = 0f; origin.Sx = 1f; origin.Sy = 1f;");
            sb.AppendLine("    for (int i = 0; i < RigBones.Length; i++) {");
            sb.AppendLine("        var bone = RigBones[i];");
            sb.AppendLine("        float lx = bone.LocalX, ly = bone.LocalY, lr = bone.LocalRot, lsx = bone.LocalSx, lsy = bone.LocalSy;");
            sb.AppendLine("        bool has;");
            sb.AppendLine("        float kx, ky, kr, ksx, ksy;");
            sb.AppendLine("        RigSampleTrack(RigClipTracks[i], clipT, out kx, out ky, out kr, out ksx, out ksy, out has);");
            sb.AppendLine("        if (has) { lx = kx; ly = ky; lr = kr; lsx = ksx; lsy = ksy; }");
            sb.AppendLine("        var parent = bone.ParentIndex >= 0 && bone.ParentIndex < i ? outBones[bone.ParentIndex] : origin;");
            sb.AppendLine("        outBones[i] = RigCompose(parent, lx, ly, lr, lsx, lsy);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitTimeField(StringBuilder sb)
        {
            sb.AppendLine("// ── Wall-clock time source for the rig clip ─────────────────");
            sb.AppendLine("// _rigTime is derived from UTC time, modulo a 3600-second window, so a");
            sb.AppendLine("// fresh recompile of the user code still produces a live frame at the");
            sb.AppendLine("// current wall-clock position in the loop. The modulo is critical:");
            sb.AppendLine("// a raw (UtcNow - epoch).TotalSeconds is hundreds of millions of seconds,");
            sb.AppendLine("// which exceeds float's ~7-digit precision and quantizes to ~16-second");
            sb.AppendLine("// steps — pinning the rig at a single pose. We do the modulo in double");
            sb.AppendLine("// precision and only cast at the end to keep sub-second resolution.");
            sb.AppendLine("// 3600 is divisible by every reasonable clip duration, so loops still align.");
            sb.AppendLine("// RigTimeStep is kept for backwards compatibility with older wire blocks.");
            sb.AppendLine("private static float _rigTime { get {");
            sb.AppendLine("    double s = System.DateTime.UtcNow.TimeOfDay.TotalSeconds % 3600.0;");
            sb.AppendLine("    return (float)s;");
            sb.AppendLine("} }");
            sb.AppendLine("private const float RigTimeStep = 0f;");
            sb.AppendLine();
        }

        /// <summary>
        /// Emits an in-frame helper that adds every bound sprite into an
        /// already-open <c>MySpriteDrawFrame</c>, sampling poses from the rig clip.
        /// Hosts call this from inside their existing <c>using (var frame = surface.DrawFrame())</c>
        /// block, so it composes with their own static sprites instead of nesting frames.
        /// </summary>
        private static void EmitAddRigSpritesMethod(StringBuilder sb, LcdLayout layout, Rig rig)
        {
            sb.AppendLine("// ── Add bound rig sprites into an existing frame ─────────────");
            sb.AppendLine("// Call from inside your DrawFrame using-block:");
            sb.AppendLine("//   AddRigSprites(frame, _rigTime); _rigTime += RigTimeStep;");
            sb.AppendLine("private void AddRigSprites(MySpriteDrawFrame frame, float time)");
            sb.AppendLine("{");
            sb.AppendLine("    // [RIG-DIAG] Surfaces the value of `time` to the Console tab so we can");
            sb.AppendLine("    // confirm wall-clock advancement per frame. Remove once verified.");
            sb.AppendLine("    try { Echo(\"[rig] t=\" + time.ToString(\"0.000\", System.Globalization.CultureInfo.InvariantCulture)); } catch { }");
            sb.AppendLine("    var bones = new RigXform[RigBones.Length];");
            sb.AppendLine("    RigEvaluate(time, bones);");
            sb.AppendLine("    try { var _b0 = bones.Length > 0 ? bones[0] : default(RigXform); Echo(\"[rig] bone0 R=\" + _b0.R.ToString(\"0.000\", System.Globalization.CultureInfo.InvariantCulture)); } catch { }");
            sb.AppendLine();

            // Map sprite index -> first matching binding (mirrors EmitDrawMethod).
            var sprites = layout.Sprites ?? new List<SpriteEntry>();
            var bindingFor = new Dictionary<int, SpriteBinding>();
            if (rig.Bindings != null)
            {
                foreach (var bd in rig.Bindings)
                    if (bd != null && !bd.Muted && bd.SpriteIndex >= 0 && bd.SpriteIndex < sprites.Count
                        && !bindingFor.ContainsKey(bd.SpriteIndex)) bindingFor[bd.SpriteIndex] = bd;
            }
            var boneIndex = new Dictionary<string, int>(rig.Bones.Count);
            for (int i = 0; i < rig.Bones.Count; i++)
                if (rig.Bones[i] != null && !string.IsNullOrEmpty(rig.Bones[i].Id))
                    boneIndex[rig.Bones[i].Id] = i;

            for (int i = 0; i < sprites.Count; i++)
            {
                var sp = sprites[i];
                if (sp == null || sp.IsHidden) continue;
                SpriteBinding bd; bindingFor.TryGetValue(i, out bd);
                int bi = -1;
                if (bd != null && !string.IsNullOrEmpty(bd.BoneId)) boneIndex.TryGetValue(bd.BoneId, out bi);
                if (bd == null || bi < 0) continue; // unbound sprites stay in user's static draw

                sb.AppendLine($"    // [{i}] {Esc(sp.DisplayName)}");
                sb.AppendLine($"    {{ var b = bones[{bi}];");
                sb.AppendLine($"      float c = (float)System.Math.Cos(b.R), s = (float)System.Math.Sin(b.R);");
                sb.AppendLine($"      float px = b.X + ({F(bd.OffsetX)} * b.Sx) * c - ({F(bd.OffsetY)} * b.Sy) * s;");
                sb.AppendLine($"      float py = b.Y + ({F(bd.OffsetX)} * b.Sx) * s + ({F(bd.OffsetY)} * b.Sy) * c;");
                sb.AppendLine($"      float pr = b.R + {F(bd.RotationOffset)};");
                sb.AppendLine($"      float psx = b.Sx * {F(bd.ScaleX)};");
                sb.AppendLine($"      float psy = b.Sy * {F(bd.ScaleY)};");
                EmitSpriteAddIndented(sb, sp, "        ", posExpr: "new Vector2(px, py)",
                    rotOrScaleExpr: PoseRotOrScale(sp), sizeExpr: PoseSize(sp));
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        /// <summary>Variant of EmitSpriteAdd parameterised by indent prefix so it can
        /// emit at method scope (4 spaces) rather than the standalone DrawRig's 12.</summary>
        private static void EmitSpriteAddIndented(StringBuilder sb, SpriteEntry sp, string ind,
            string posExpr, string rotOrScaleExpr, string sizeExpr)
        {
            sb.AppendLine(ind + "frame.Add(new MySprite {");
            if (sp.Type == SpriteEntryType.Text)
            {
                sb.AppendLine(ind + "    Type = SpriteType.TEXT,");
                sb.AppendLine(ind + $"    Data = \"{Esc(sp.Text)}\",");
                sb.AppendLine(ind + $"    Position = {posExpr},");
                sb.AppendLine(ind + $"    Color = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                sb.AppendLine(ind + $"    FontId = \"{Esc(sp.FontId)}\",");
                sb.AppendLine(ind + $"    Alignment = TextAlignment.{sp.Alignment.ToString().ToUpperInvariant()},");
                sb.AppendLine(ind + $"    RotationOrScale = {rotOrScaleExpr},");
            }
            else
            {
                sb.AppendLine(ind + "    Type = SpriteType.TEXTURE,");
                sb.AppendLine(ind + $"    Data = \"{Esc(sp.SpriteName)}\",");
                sb.AppendLine(ind + $"    Position = {posExpr},");
                sb.AppendLine(ind + $"    Size = {sizeExpr},");
                sb.AppendLine(ind + $"    Color = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                sb.AppendLine(ind + "    Alignment = TextAlignment.CENTER,");
                sb.AppendLine(ind + $"    RotationOrScale = {rotOrScaleExpr},");
            }
            sb.AppendLine(ind + "});");
        }

        private static void EmitDrawMethod(StringBuilder sb, LcdLayout layout, Rig rig, string methodName, string surfaceParam)
        {
            // Build set of bound sprite indices so we know which sprites get rig poses
            // and which fall back to literal layout positions.
            var bound = new HashSet<int>();
            if (rig.Bindings != null)
                foreach (var bd in rig.Bindings)
                    if (bd != null && !bd.Muted && bd.SpriteIndex >= 0) bound.Add(bd.SpriteIndex);

            sb.AppendLine("// ── Draw entry point ─────────────────────────────────────────");
            sb.AppendLine("// Standalone helper for hosts that don't have an existing DrawFrame block.");
            sb.AppendLine("// Bound sprites are emitted via AddRigSprites; only unbound sprites are inlined here,");
            sb.AppendLine("// so editing the rig only updates one place.");
            sb.AppendLine($"public void {methodName}(IMyTextSurface {surfaceParam}, float time)");
            sb.AppendLine("{");
            sb.AppendLine($"    {surfaceParam}.ContentType = ContentType.SCRIPT;");
            sb.AppendLine($"    {surfaceParam}.Script = \"\";");
            sb.AppendLine();
            sb.AppendLine($"    using (var frame = {surfaceParam}.DrawFrame())");
            sb.AppendLine("    {");
            sb.AppendLine("        AddRigSprites(frame, time);");

            // Inline only unbound sprites here — bound ones live in AddRigSprites.
            var sprites = layout.Sprites ?? new List<SpriteEntry>();
            var bindingFor = new Dictionary<int, SpriteBinding>();
            if (rig.Bindings != null)
                foreach (var bd in rig.Bindings)
                    if (bd != null && !bd.Muted && bd.SpriteIndex >= 0 && bd.SpriteIndex < sprites.Count
                        && !bindingFor.ContainsKey(bd.SpriteIndex)) bindingFor[bd.SpriteIndex] = bd;

            for (int i = 0; i < sprites.Count; i++)
            {
                var sp = sprites[i];
                if (sp == null || sp.IsHidden) continue;
                if (bindingFor.ContainsKey(i)) continue; // bound: handled by AddRigSprites

                sb.AppendLine($"        // [{i}] {Esc(sp.DisplayName)} (unbound)");
                EmitSpriteAdd(sb, sp,
                    posExpr: $"new Vector2({F(sp.X)}, {F(sp.Y)})",
                    rotOrScaleExpr: F(sp.Type == SpriteEntryType.Text ? sp.Scale : sp.Rotation),
                    sizeExpr: $"new Vector2({F(sp.Width)}, {F(sp.Height)})");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
        }

        private static string PoseRotOrScale(SpriteEntry sp)
        {
            if (sp.Type == SpriteEntryType.Text)
            {
                // Apply binding+bone scale on top of authored text scale.
                return $"{F(sp.Scale)} * ((psx + psy) * 0.5f)";
            }
            return "pr + " + F(sp.Rotation);
        }

        private static string PoseSize(SpriteEntry sp)
        {
            return $"new Vector2({F(sp.Width)} * psx, {F(sp.Height)} * psy)";
        }

        private static void EmitSpriteAdd(StringBuilder sb, SpriteEntry sp, string posExpr, string rotOrScaleExpr, string sizeExpr)
        {
            sb.AppendLine("            frame.Add(new MySprite {");
            if (sp.Type == SpriteEntryType.Text)
            {
                sb.AppendLine("                Type = SpriteType.TEXT,");
                sb.AppendLine($"                Data = \"{Esc(sp.Text)}\",");
                sb.AppendLine($"                Position = {posExpr},");
                sb.AppendLine($"                Color = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                sb.AppendLine($"                FontId = \"{Esc(sp.FontId)}\",");
                sb.AppendLine($"                Alignment = TextAlignment.{sp.Alignment.ToString().ToUpperInvariant()},");
                sb.AppendLine($"                RotationOrScale = {rotOrScaleExpr},");
            }
            else
            {
                sb.AppendLine("                Type = SpriteType.TEXTURE,");
                sb.AppendLine($"                Data = \"{Esc(sp.SpriteName)}\",");
                sb.AppendLine($"                Position = {posExpr},");
                sb.AppendLine($"                Size = {sizeExpr},");
                sb.AppendLine($"                Color = new Color({sp.ColorR}, {sp.ColorG}, {sp.ColorB}, {sp.ColorA}),");
                sb.AppendLine("                Alignment = TextAlignment.CENTER,");
                sb.AppendLine($"                RotationOrScale = {rotOrScaleExpr},");
            }
            sb.AppendLine("            });");
        }

        // ─────────────────────────────────────────────────────────────────────
        // Helpers
        // ─────────────────────────────────────────────────────────────────────
        private static string F(float v) => v.ToString("0.0####", Inv) + "f";

        private static string Esc(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
        }
    }
}
